### ISSUE TITLE
Game crashing in 1.16.3

### ISSUE THREAD

**Issue by Viruzaum** [ModsByLeo/DontDropIt#12]
Crash happens even if I have only DontDropIt and FabricAPI

Minecraft version: 1.16.3
Java version: 11.0.7 GraalVM

This is the only info in the log:
`[05:03:39] [main/INFO]: Loading for game Minecraft 1.16.3
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsupportedOperationException: Call the solve method first!!!
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.model(Solver.java:498)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:223)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:604)
	at **net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:202)**
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Exiting with -1
Process exited with code -1.`

**Comment by Leo40Git** [comment]
2.0.0 will be compatible with 1.16.3.
